[package]
name = "owlauth-storage"
description = "Storage abstractions for the OwlAuth server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
owlauth-domain = { path = "../domain" }

[lints]
workspace = true
