[package]
name = "owlauth-client"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
description = "Rust client for OwlAuth"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["oauth", "oauth2", "authentication", "client"]
categories = ["authentication", "api-bindings"]

[lints]
workspace = true
