[package]
name = "owlauth-client"
version = "0.0.1"
edition.workspace = true
description = "Rust Project Auth client for OwlAuth"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["authentication", "identity", "project-auth", "client"]
categories = ["authentication", "api-bindings"]

[lints]
workspace = true
