[package]
name = "owlauth-server"
version = "0.0.2"
edition.workspace = true
description = "Self-hostable Project Auth and identity server"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["authentication", "identity", "self-hosted", "server"]
categories = ["authentication", "web-programming::http-server"]

[dependencies]
axum = "0.8.9"
owlauth-types = { version = "=0.0.2", path = "../owlauth-types" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net"] }

[lints]
workspace = true

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
