[package]
name = "owlauth-cli"
version = "0.0.0-dev"
edition.workspace = true
description = "Control command-line interface for OwlAuth"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["authentication", "identity", "management", "cli"]
categories = ["authentication", "command-line-utilities"]
include = ["src/**", "assets/**", "README.md", "LICENSE"]

[[bin]]
name = "owlauth"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
owlauth-types = { version = "=0.0.0-dev", path = "../owlauth-types" }
reqwest = { version = "0.13.1", default-features = false, features = ["blocking", "json", "rustls"] }
semver = "1.0.27"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
thiserror = "2.0.18"
url = "2.5.8"
uuid = "1.19.0"
zeroize = "1.8.2"
