[package]
name = "owlauth"
description = "Self-hostable OAuth 2.1 authorization server and user management platform"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
axum = "0.8.9"
owlauth-domain = { path = "../domain" }
owlauth-protocol = { path = "../protocol" }
owlauth-storage = { path = "../storage" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net"] }

[lints]
workspace = true

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
