-- Validate the additive authority bounds with DML-compatible validation locks.

ALTER TABLE provider_configurations
    VALIDATE CONSTRAINT provider_configurations_onboarding_policy_revision_check;
ALTER TABLE provider_secret_operations
    VALIDATE CONSTRAINT provider_secret_operations_egress_policy_revision_check;
ALTER TABLE identity_mutation_proof_slots
    VALIDATE CONSTRAINT identity_mutation_proof_slots_provider_egress_policy_revision_check;
ALTER TABLE managed_provider_reauthorization_interactions
    VALIDATE CONSTRAINT managed_provider_reauthorization_provider_egress_policy_revision_check;
ALTER TABLE managed_provider_renewal_operations
    VALIDATE CONSTRAINT managed_provider_renewal_provider_egress_policy_revision_check;
ALTER TABLE login_transaction_methods
    VALIDATE CONSTRAINT login_transaction_methods_provider_kind_check;
ALTER TABLE login_transaction_methods
    VALIDATE CONSTRAINT login_transaction_methods_provider_egress_policy_revision_check;
