-- Validate SMTP custody references and the backfilled deployment owner identity with DML-compatible
-- validation locks.

ALTER TABLE project_smtp_configurations
    VALIDATE CONSTRAINT project_smtp_configurations_credential_material_id_fkey;
ALTER TABLE project_smtp_secret_operations
    VALIDATE CONSTRAINT project_smtp_secret_operations_material_id_fkey;
ALTER TABLE project_smtp_test_operations
    VALIDATE CONSTRAINT project_smtp_test_operations_credential_material_id_fkey;
ALTER TABLE project_smtp_test_operations
    VALIDATE CONSTRAINT project_smtp_test_operations_recipient_material_id_fkey;
ALTER TABLE deployment_smtp_generations
    VALIDATE CONSTRAINT deployment_smtp_generations_credential_material_id_fkey;
ALTER TABLE deployment_smtp_generations
    VALIDATE CONSTRAINT deployment_smtp_material_owner_not_null_check;
ALTER TABLE smtp_credential_cleanup_operations
    VALIDATE CONSTRAINT smtp_credential_cleanup_operations_material_id_fkey;
ALTER TABLE smtp_credential_reference_reservations
    VALIDATE CONSTRAINT smtp_credential_reference_reservations_material_id_fkey;
ALTER TABLE smtp_test_recipient_reference_reservations
    VALIDATE CONSTRAINT smtp_test_recipient_reference_reservations_material_id_fkey;
